
export interface ExerciseCategory {
  label: string;
  exercises: string[];
}

export const EXERCISE_DATABASE: ExerciseCategory[] = [
  {
    label: 'CALENTAMIENTO',
    exercises: [
      'Jumping Jacks',
      'Rodillas altas',
      'Talones al glúteo',
      'Rotación de brazos',
      'Rotación de tronco',
      'Estocadas dinámicas',
      'Marcha en el sitio',
      'Círculos de cadera',
      'Rotación de tobillos',
      'Balanceo de piernas',
      'Sentadillas laterales dinámicas',
      'Gato-Vaca dinámico',
      'Giro de muñecas',
      'Círculos con los hombros',
      'Escaladores lentos',
      'Paseo del oso suave',
      'Estiramiento de cobra dinámico',
      'Torsión de columna en T',
      'Puente de glúteo isométrico',
      'Activación de escápulas',
      'Desplazamiento lateral',
      'Sombra de boxeo',
      'Apertura de cadera Spiderman',
      'Giro de cuello suave',
      'Flexión de rodillas al pecho',
      'Patadas frontales suaves',
      'Salto a la comba imaginaria',
      'Plancha dinámica',
      'Paso lateral rítmico',
      'Movilidad de dedos y manos'
    ]
  },
  {
    label: 'HIIT',
    exercises: [
      'Burpees',
      'Escaladores (Mountain Climbers)',
      'Sentadillas con salto',
      'Saltos agrupados (Tuck Jumps)',
      'Saltos al cajón',
      'Sprints en el sitio',
      'Saltos de patinador',
      'Plancha con saltos (Plank Jacks)',
      'Flexiones Spiderman',
      'Paseo del oso explosivo',
      'Burpees con flexión',
      'Zancadas con salto',
      'Saltos de longitud',
      'Saltos de estrella',
      'Plancha con toque de hombros',
      'Escalador cruzado',
      'Salto de comba rápido',
      'Saltos de rana',
      'Saltos laterales sobre objeto',
      'Thrusters (sin peso)',
      'Sentadilla con rodillazo',
      'Burpee lateral',
      'Zancada lateral con salto',
      'Plancha con salto adelante',
      'Sprint lateral',
      'Saltos Heidman',
      'Escalador explosivo',
      'Burpee con giro 180',
      'Zancadas alternas rápidas',
      'Doble salto de rodilla'
    ]
  },
  {
    label: 'TREN SUPERIOR',
    exercises: [
      'Flexiones clásicas',
      'Flexiones diamante',
      'Flexiones declinadas',
      'Fondos de tríceps',
      'Flexiones en pica',
      'Plancha estática',
      'Plancha lateral',
      'Superman',
      'Remo invertido',
      'Flexiones en pared',
      'Flexiones de arquero',
      'Flexiones con aplauso',
      'Flexiones inclinadas',
      'Plancha con extensión de brazos',
      'Plancha lateral con rotación',
      'Superman con nado',
      'Paseo de plancha lateral',
      'Flexiones en T',
      'Bird Dog (Pájaro-Perro)',
      'Hollow Body Hold',
      'Pica con pies elevados',
      'Toque de pies en plancha',
      'Caminata de gusano',
      'Flexión a plancha lateral',
      'Flexiones de hombro en pared',
      'Plancha con elevación de pierna',
      'Fondos en silla profunda',
      'Abdominales en V',
      'Dead Bug (Bicho muerto)',
      'Plancha comando'
    ]
  },
  {
    label: 'TREN INFERIOR',
    exercises: [
      'Sentadillas',
      'Sentadillas sumo',
      'Zancadas',
      'Zancadas laterales',
      'Peso muerto rumano',
      'Puente de glúteo',
      'Elevación de pantorrillas',
      'Sentadilla búlgara',
      'Step-ups',
      'Sentadilla en pared (Wall Sit)',
      'Sentadilla con salto lateral',
      'Zancada hacia atrás',
      'Zancada cruzada',
      'Puente de glúteo a una pierna',
      'Abducción lateral de cadera',
      'Sentadilla isométrica',
      'Patada de glúteo',
      'Boca de incendio (Fire Hydrants)',
      'Sentadilla con talones elevados',
      'Zancada frontal a trasera',
      'Peso muerto a una pierna',
      'Sentadilla Cossack',
      'Salto de cajón bajo',
      'Zancada caminando',
      'Elevación de rodilla equilibrada',
      'Sentadilla con toque de suelo',
      'Paseo lateral en sentadilla',
      'Extensión de cadera de pie',
      'Sentadilla con pulso',
      'Zancada lateral explosiva'
    ]
  },
  {
    label: 'ENFRIAMIENTO',
    exercises: [
      'Estiramiento de cuádriceps',
      'Estiramiento de isquiotibiales',
      'Estiramiento de gemelos',
      'Estiramiento de hombros',
      'Estiramiento de tríceps',
      'Estiramiento de pecho',
      'Postura del niño',
      'Torsión espinal sentado',
      'Estiramiento de cadera',
      'Respiración profunda',
      'Perro boca abajo',
      'Estiramiento de psoas',
      'Postura de la paloma',
      'Estiramiento lateral',
      'Estiramiento de cuello',
      'Postura del bebé feliz',
      'Rodillas al pecho',
      'Estiramiento de muñecas',
      'Postura de la esfinge',
      'Estiramiento mariposa',
      'Respiración 4-7-8',
      'Estiramiento de antebrazos',
      'Torsión de columna acostado',
      'Cobra suave',
      'Relajación progresiva',
      'Estiramiento de fascia plantar',
      'Apertura de pecho en pared',
      'Estiramiento de trapecio',
      'Flexión frontal sentado',
      'Meditación de cierre'
    ]
  }
];

export const ALL_EXERCISES = EXERCISE_DATABASE.flatMap(cat => cat.exercises);
